fix(mkmr): return the correct type from find_config()
os.Path does not exist, os.path is the correct type.

This fixes:

AttributeError: module 'os' has no attribute 'Path'